# Generated by Django 4.1.11 on 2023-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('first_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=20)),
                ('phone_Number', models.CharField(max_length=10)),
                ('adhar_Number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('rfid', models.IntegerField()),
            ],
        ),
    ]
